#!/bin/bash

#PBS -P RDS-FEI-RICARDO_01-RW                
#PBS -l select=7:ncpus=32:mpiprocs=234:mem=120GB
#PBS -l walltime=24:00:00
#PBS -N MPI_Ricardo_Simulator
#PBS -m abe
#PBS -M xwan0069@uni.sydney.edu.au

module load python/3.8.2 pandas/2.0.3 gurobi/9.1.2 openmpi-gcc/4.0.3
cd /project/RDS-FEI-RICARDO_01-RW/simulator_data_collector/Simulator
mpirun -np 234 python multi_main_mpi.py> output.log 2> error.log